config/routes.rb
Mbraids::Application.routes.draw do

  root :to => 'application#index'

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'} #, :path_name => {:sign_up => "register"} #this is to change the default
  resources :authentications

  scope "(:locale)", :locale => /en|ru/ do
    match 'ladies' => 'hairstyle_collections#ladies'
    match 'girls' => 'hairstyle_collections#girls'
    resources :hairstyle_collections do
      resources :hairstyles
    end
  end

  scope "(:locale)", :locale => /en|ru/ do
    match 'accessories' => 'categories#index'
    match 'book_appointment' => 'appointments#book'
    resources :accessories, :except => :index
    resources :appointments
    resources :categories do
      resources :accessories
    end
    resources :accounts
    resources :orders
    resource :quote_box do
      resources :line_items
    end
    match 'attach_image' => 'orders#add_image', :via => [:post]
    match 'portfolio' => 'hairstyle_collections#index'
  end

  match '/:locale' => 'application#index'

end

app/models/quote_box.rb
class QuoteBox < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :order
  attr_accessible :order_id
  def add_item(item)
    if item.is_a?(Appointment) and li = line_items.find_by_quotable_type(Appointment.to_s)
      li.errors.add(:base, "you already selected an appointment")
      return li
    end
    #try to find the same class and id in the quote box
    line_items.each do |li|
      if li.quotable_type == item.class.to_s and li.quotable_id == item.id
        if item.class.to_s == "Appointment"
        end
        li.quantity += 1
        return li
      end
    end
    return line_items.build(quotable: item)
  end
end

app/controllers/quote_boxes_controller.rb
class QuoteBoxesController < ApplicationController
  # GET /quote_boxes
  # GET /quote_boxes.json
  def index
    @quote_boxes = QuoteBox.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quote_boxes }
    end
  end

  # GET /quote_boxes/1
  # GET /quote_boxes/1.json
  def show
    @quote_box = current_quote_box(true)
    #TODO: redo this with quicker select sql.
    @hairstyles = []
    @accessories = []
    @appointments = []

    @accessories_2 = Accessory.paginate(page: params[:page], per_page: 2)

    if @quote_box
      @quote_box.line_items.each do |line_item|
        @hairstyles << [Hairstyle.find(line_item.quotable_id),line_item.id] if line_item.quotable_type == "Hairstyle"
        @accessories << [Accessory.find(line_item.quotable_id),line_item.id] if line_item.quotable_type == "Accessory"
        @appointments << [Appointment.find(line_item.quotable_id),line_item.id] if line_item.quotable_type == "Appointment"
      end
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote_box }
    end
  end

  # GET /quote_boxes/new
  # GET /quote_boxes/new.json
  def new
    @quote_box = QuoteBox.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote_box }
    end
  end

  # GET /quote_boxes/1/edit
  def edit
    @quote_box = QuoteBox.find(params[:id])
  end

  # POST /quote_boxes
  # POST /quote_boxes.json
  def create
    @quote_box = QuoteBox.new(params[:quote_box])

    respond_to do |format|
      if @quote_box.save
        format.html { redirect_to @quote_box, notice: 'Quote box was successfully created.' }
        format.json { render json: @quote_box, status: :created, location: @quote_box }
      else
        format.html { render action: "new" }
        format.json { render json: @quote_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quote_boxes/1
  # PUT /quote_boxes/1.json
  def update
    @quote_box = QuoteBox.find(params[:id])

    respond_to do |format|
      if @quote_box.update_attributes(params[:quote_box])
        format.html { redirect_to @quote_box, notice: 'Quote box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote_boxes/1
  # DELETE /quote_boxes/1.json
  def destroy
    @quote_box = current_quote_box
    @quote_box.destroy
    session[:quote_box_id] = nil

    respond_to do |format|
      format.html { redirect_to quote_box_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/quote_boxes_helper.rb
module QuoteBoxesHelper
end

app/views/quote_boxes/_form.html.slim
= form_for @quote_box do |f|
  - if @quote_box.errors.any?
    #error_explanation
      h2 = "#{pluralize(@quote_box.errors.count, "error")} prohibited this quote_box from being saved:"
      ul
        - @quote_box.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :appointment_id
    = f.number_field :appointment_id
  .actions = f.submit 'Save'

app/views/quote_boxes/edit.html.slim
h1 Editing quote_box

== render 'form'

= link_to 'Show', @quote_box
'|
= link_to 'Back', quote_boxes_path

app/views/quote_boxes/index.html.slim
h1 Listing quote_boxes

table
  tr
    th Appointment
    th
    th
    th

  - @quote_boxes.each do |quote_box|
    tr
      td = quote_box.appointment_id
      td = link_to 'Show', quote_box
      td = link_to 'Edit', edit_quote_box_path(quote_box)
      td = link_to 'Destroy', quote_box, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Quote box', new_quote_box_path

app/views/quote_boxes/new.html.slim
h1 New quote_box

== render 'form'

= link_to 'Back', quote_boxes_path

app/views/quote_boxes/show.html.slim
h2=t('.sample_quote_box')
-unless @hairstyles.empty?
  h3=t('.hairstyles')

  -@hairstyles.each do |hs, li|
    div
      span=hs.name
      span= button_to(t('.remove'),quote_box_line_item_path(id: li), {:confirm => t('.confirm_deletion'), :method => :delete})
-unless @accessories.empty?
  h3=t('.accessories')
  -@accessories.each do |ac, li|
    div
      span=ac.name
      span= button_to(t('.remove'),quote_box_line_item_path(id: li), {:confirm => t('.confirm_deletion'), :method => :delete})
-unless @appointments.empty?
  h3=t('.appointments')
  -@appointments.each do |ap,li|
    div
      span=ap.description
      span=ap.apt_date
      span=ap.apt_time
      span= button_to(t('.remove'),quote_box_line_item_path(id: li), {:confirm => t('.confirm_deletion'), :method => :delete})

-unless @quote_box
  .row
    .offset2
    - @accessories_2.each do |acc|
      .span1
        =link_to(image_tag(acc.image, {class: "img-polaroid"}), accessory_path(acc))
  =will_paginate(@accessories_2, {class: "pagination pagination-right", renderer: BootstrapPagination::Rails})
  /ul
  /  li=link_to("&laquo;".html_safe, root_path)
  /  li=link_to("1", root_path)
  /  li=link_to("2", root_path)
  /  li=link_to("3", root_path)
  /  li=link_to("4", root_path)
  /  li=link_to("&raquo;".html_safe, root_path)


  p=t('.emtpy_message')
-if @quote_box
  =link_to(t('.destroy'), quote_box_path, :confirm => t('.confirm_deletion'), :method => :delete)
  =button_to(t('.confirm_order'), orders_path, {:confirm => t('.confirm_order_msg')})


.page-header
  h2=t('.quote_box')
  small
    =t('.sub_header')
    =render partial: "show_info_message"
-unless @hairstyles.empty?
  h3=t('.hairstyles')
  table.table(class="table-striped")
    thead
      tr
        th=t('common.table.name')
        th=t('common.table.image')
        th=t('common.table.price')
        th=t('common.table.description')
        th=t('common.table.action')
    tbody
      =render :partial => 'hairstyle', :collection => @hairstyles
='link_to(t('.new_hairstyle'),new_hairstyle_collection_hairstyle_path, class: "btn btn-primary")
=link_to(t('.hairstyle_collections_btn'),:back, class: "btn")