config/routes.rb
Mbraids::Application.routes.draw do

  root :to => 'application#index'

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'} #, :path_name => {:sign_up => "register"} #this is to change the default
  resources :authentications

  scope "(:locale)", :locale => /en|ru/ do
    match 'ladies' => 'hairstyle_collections#ladies'
    match 'girls' => 'hairstyle_collections#girls'
    resources :hairstyle_collections do
      resources :hairstyles
    end
  end

  scope "(:locale)", :locale => /en|ru/ do
    match 'accessories' => 'categories#index'
    match 'book_appointment' => 'appointments#book'
    resources :accessories, :except => :index
    resources :appointments
    resources :categories do
      resources :accessories
    end
    resources :accounts
    resources :orders
    resource :quote_box do
      resources :line_items
    end
    match 'attach_image' => 'orders#add_image', :via => [:post]
    match 'portfolio' => 'hairstyle_collections#index'
  end

  match '/:locale' => 'application#index'

end

app/models/hairstyle_collection.rb
class HairstyleCollection < ActiveRecord::Base
  #TODO: need to add index for the intermediate table!
  has_and_belongs_to_many :hairstyles
  attr_accessible :name, :description, :collection_type
  validates_presence_of :name
end

app/controllers/hairstyle_collections_controller.rb
class HairstyleCollectionsController < ApplicationController
  def index

  end

  def ladies
    @h2_header_prefix = "l"
    @hairstyle_collections = HairstyleCollection.where(["displayable_flag = ? and collection_type = ?",
    true, 'L'])
    respond_to do |format|
      format.html {render :collection_list}
    end
  end
  def girls
    @h2_header_prefix = "g"
    @hairstyle_collections = HairstyleCollection.where(["displayable_flag = ? and collection_type = ?",
    true, 'G'])
    respond_to do |format|
      format.html {render :collection_list}
    end
  end


  def new
    @hairstyle_collection = HairstyleCollection.new
  end

  def create
    @hairstyle_collection = HairstyleCollection.new(params[:hairstyle_collection])

    logger.debug(@hairstyle_collection.inspect)

    respond_to do |format|
      if @hairstyle_collection.save
        format.html {redirect_to hairstyle_collections_path, notice: '.create_hairstyle_collection_successful'}
      else
        format.html {render action: 'new', alert: '.create_hairstyle_collection_unsuccessful'}
      end
    end
  end

  def edit
    @hairstyle_collection = HairstyleCollection.find(params[:id])
  end

  def update
    @hairstyle_collection = HairstyleCollection.find(params[:id])

    respond_to do |format|
      if @hairstyle_collection.update_attributes(params[:hairstyle_collection])
        format.html { redirect_to hairstyle_collections_path, notice: '.update_hairstyle_collection_successful' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hairstyle_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hairstyle_collection = HairstyleCollection.find(params[:id])
    #TODO: see if this child deletion can be done better
    @hairstyle_collection.hairstyles.each do |hairstyle|
      begin
        File.delete(Rails.root.join('app','assets','uploads',hairstyle.image))
      rescue

      end
      hairstyle.destroy
    end
    @hairstyle_collection.destroy

    respond_to do |format|
      format.html { redirect_to hairstyle_collections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hairstyle_collections_helper.rb
module HairstyleCollectionsHelper
end

app/views/hairstyle_collections/_form.html.slim
= form_for @hairstyle_collection, html: {class: "form-horizontal"} do |f|
  fieldset

    legend =t("." + "#{action_name}" + "_collection")
    =render(partial: 'show_error_message', locals: {obj: @hairstyle_collection})
    div.control-group(class="#{field_has_error?(@hairstyle_collection, :name) ? "error" : ""}")
      =f.label :name, t('common.form.name'), class: "control-label"
      .controls
        = f.text_field :name, {placeholder: t("common.form.name"), class: "text_field input-medium"}
        - if field_has_error?(@hairstyle_collection, :name)
          span.help-inline=get_field_error(@hairstyle_collection, :name)
    div.control-group(class="#{field_has_error?(@hairstyle_collection, :description) ? "error" : ""}")
      =f.label :description, t('common.form.description'), class: "control-label"
      .controls
        = f.text_field :description, {placeholder: t("common.form.description"), class: "text_field input-medium"}
        - if field_has_error?(@hairstyle_collection, :description)
          span.help-inline=get_field_error(@hairstyle_collection, :description)
    div.control-group(class="#{field_has_error?(@hairstyle_collection, :collection_type) ? "error" : ""}")
      =f.label :collection_type, t('common.form.collection_type'), class: "control-label"
      .controls
        = f.select :collection_type, [%w(Ladies L),%w(Girls G)]
        - if field_has_error?(@hairstyle_collection, :collection_type)
          span.help-inline=get_field_error(@hairstyle_collection, :collection_type)
    .form-actions
      ='f.submit t('common.form.save'), {class: "btn btn-primary"}
      =link_to(t('common.form.cancel'), :back, {class: "btn"})

app/views/hairstyle_collections/_form_wrapper.html.slim
-if @hairstyle_collection.errors.size > 0
  .message
    .ui-widget
      div(class="ui-state-error ui-corner-all" style='padding: 0 .7em;')
        p
          span(class='ui-icon ui-icon-alert' style='float: left; margin-right: .3em;')
          |
          =t('.saving_form_data_error')
/-if @account.errors.size > 0
/  .message
/    .ui-widget
/      div(class="ui-state-highlight ui-corner-all" style='padding: 0 .7em;')
/        p
/          span(class='ui-icon ui-icon-info' style='float: left; margin-right: .3em;')
/          -@account.errors.each do |field, message|
/            =field.to_s.concat(" #{message}").html_safe
/            br
= render "form"

app/views/hairstyle_collections/_hairstyle_collection.html.slim
tr
  //there was a problem with not passing the hairstyle_collection parameter here - spend a few hours on this
  td= link_to(hairstyle_collection.name, hairstyle_collection_hairstyles_path(hairstyle_collection), {class: "btn"})
  td= hairstyle_collection.description
  td
    span='link_to(t('.edit'), edit_hairstyle_collection_path(hairstyle_collection), {class: "btn"})
    span='link_to(t('.destroy'), hairstyle_collection, :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger")






app/views/hairstyle_collections/collection_list.html.slim
.page-header
  h2=t('.header')
  small
    =t('.sub_header')
    =render partial: "show_info_message"
table.table(class="table-striped")
  thead
    tr
      th=t('common.table.name')
      th=t('common.table.description')
      th=t('common.table.action')
  tbody
    =render :partial => 'hairstyle_collection', :collection => @hairstyle_collections
='link_to(t('.new_collection'),new_hairstyle_collection_path, class: "btn btn-primary")
=link_to(t('.collections_btn'),hairstyle_collections_path, class: "btn")

app/views/hairstyle_collections/edit.html.slim
.row
  .span8(class="offset2")
    == render 'form'

app/views/hairstyle_collections/index.html.slim
h2 here are the collections

=' link_to(t('.luxemburg'),ladies_path)
=link_to(t('.greenwitch'),girls_path)

app/views/hairstyle_collections/new.html.slim
.row
  .span8(class="offset2")
    == render 'form'