config/routes.rb
Mbraids::Application.routes.draw do

  root :to => 'application#index'

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'} #, :path_name => {:sign_up => "register"} #this is to change the default
  resources :authentications

  scope "(:locale)", :locale => /en|ru/ do
    match 'ladies' => 'hairstyle_collections#ladies'
    match 'girls' => 'hairstyle_collections#girls'
    resources :hairstyle_collections do
      resources :hairstyles
    end
  end

  scope "(:locale)", :locale => /en|ru/ do
    match 'accessories' => 'categories#index'
    match 'book_appointment' => 'appointments#book'
    resources :accessories, :except => :index
    resources :appointments
    resources :categories do
      resources :accessories
    end
    resources :accounts
    resources :orders
    resource :quote_box do
      resources :line_items
    end
    match 'attach_image' => 'orders#add_image', :via => [:post]
    match 'portfolio' => 'hairstyle_collections#index'
  end

  match '/:locale' => 'application#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  #TODO: need to add index for the intermediate table!
  has_and_belongs_to_many :accessories
  attr_accessible :name, :description
  validates_presence_of :name, :description
  validates_length_of :name, :minimum => 7
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html { render :categories_list }
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    #TODO: see if this child deletion can be done better
    @category.accessories.each do |accessory|
      #begin
        File.delete(Rails.root.join('app','assets','uploads',accessory.image))
      #rescue

      #end
      accessory.destroy
    end
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/__index.html.slim
h2 Listing categories
table
  tr
    th Name
    th Destion
    th
    th
    th

  - @categories.each do |category|
    tr
      td = category.name
      td = category.description
      td = link_to 'Show', category
      td = link_to 'Edit', edit_category_path(category)
      td = link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete

br

.page-header
  h2=t('.header', in: @category.name)
  small
    =t('.sub_header')
    =render partial: "show_info_message"
table.table(class="table-striped")
  thead
    tr
      th=t('common.table.name')
      th=t('common.table.image')
      th=t('common.table.price')
      th=t('common.table.description')
      th=t('common.table.action')
  tbody
    =render :partial => 'accessory', :collection => @accessories
='link_to(t('.new_accessory'),new_category_accessory_path, class: "btn btn-primary")
=link_to(t('.categories_btn'),categories_path, class: "btn")


app/views/categories/_category.html.slim
tr
  //there was a problem with not passing the hairstyle_collection parameter here - spend a few hours on this
  td= link_to(category.name, category_accessories_path(category), {class: "btn"})
  td= category.description
  td
    span='link_to(t('common.btn.edit'), edit_category_path(category), {class: "btn"})
    span=link_to(t('common.btn.destroy'), category, {method: :delete, confirm: "are you sure?", class: "btn btn-danger"})

app/views/categories/_form.html.slim
= form_for @category, html: {class: "form-horizontal"} do |f|
  fieldset

    legend =t("." + "#{action_name}" + "_category")
    =render(partial: 'show_error_message', locals: {obj: @category})
    div.control-group(class="#{field_has_error?(@category, :name) ? "error" : ""}")
      =f.label :name, t('common.form.name'), class: "control-label"
      .controls
        = f.text_field :name, {placeholder: t("common.form.name"), class: "text_field input-medium"}
        - if field_has_error?(@category, :name)
          span.help-inline=get_field_error(@category, :name)
    div.control-group(class="#{field_has_error?(@category, :description) ? "error" : ""}")
      =f.label :description, t('common.form.description'), class: "control-label"
      .controls
        = f.text_field :description, {placeholder: t("common.form.description"), class: "text_field input-medium"}
        - if field_has_error?(@category, :description)
          span.help-inline=get_field_error(@category, :description)
    .form-actions
      ='f.submit t('common.form.save'), {class: "btn btn-primary"}
      =link_to(t('common.form.cancel'), :back, {class: "btn"})

app/views/categories/categories_list.html.slim
.page-header
  h2=t('.collections')
  small
    =t('.sub_header')
    =render partial: "show_info_message"
table.table(class="table-striped")
  thead
    tr
      th=t('common.table.name')
      th=t('common.table.description')
      th=t('common.table.action')
  tbody
    =render :partial => 'category', :collection => @categories
='link_to(t('.new_category'),new_category_path, class: "btn btn-primary")

app/views/categories/edit.html.slim
.row
  .span8(class="offset2")
    == render 'form'


app/views/categories/new.html.slim
.row
  .span8(class="offset2")
    == render 'form'

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name
p
  strong Description:
  = @category.description

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path