config/routes.rb
Mbraids::Application.routes.draw do

  root :to => 'application#index'

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'} #, :path_name => {:sign_up => "register"} #this is to change the default
  resources :authentications

  scope "(:locale)", :locale => /en|ru/ do
    match 'ladies' => 'hairstyle_collections#ladies'
    match 'girls' => 'hairstyle_collections#girls'
    resources :hairstyle_collections do
      resources :hairstyles
    end
  end

  scope "(:locale)", :locale => /en|ru/ do
    match 'accessories' => 'categories#index'
    match 'book_appointment' => 'appointments#book'
    resources :accessories, :except => :index
    resources :appointments
    resources :categories do
      resources :accessories
    end
    resources :accounts
    resources :orders
    resource :quote_box do
      resources :line_items
    end
    match 'attach_image' => 'orders#add_image', :via => [:post]
    match 'portfolio' => 'hairstyle_collections#index'
  end

  match '/:locale' => 'application#index'

end

app/models/accessory.rb
require 'shared'
class Accessory < ActiveRecord::Base
  include Shared
  has_and_belongs_to_many :categories
  has_many :line_items, :as => :quotable
  attr_accessible :image, :price, :displayable_flag, :name, :description

  before_destroy :ensure_not_referenced
  validates_presence_of :name
  private :ensure_not_referenced
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  # GET /accessories
  # GET /accessories.json
  def index
    @category = Category.find(params[:category_id])
    @accessories = @category.accessories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accessories }
    end
  end

  # GET /accessories/1
  # GET /accessories/1.json
  #def show
  #  @accessory = Accessory.find(params[:id])
  #
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @accessory }
  #  end
  #end

  # GET /accessories/new
  # GET /accessories/new.json
  def new
    @category = Category.find(params[:category_id])
    @accessory = @category.accessories.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @accessory }
    end
  end

  # GET /accessories/1/edit
  def edit
    @accessory = Accessory.find(params[:id])
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @category = Category.find(params[:category_id])
    @accessory = @category.accessories.new(params[:accessory])

    uploaded_file = params[:accessory][:image]
    @accessory.image = set_image_filename(uploaded_file.original_filename)

    respond_to do |format|
      if @category.accessories << @accessory
        #TODO: important: wb stands for write binary mode to avoid utf-8 conversion error
        File.open(Rails.root.join('app','assets','uploads',@accessory.image),'wb') do |file|
          file.write(uploaded_file.read)
        end
        format.html {redirect_to category_accessories_path, notice: '.create_accessory_successful'}
      else
        format.html {render action: 'new', alert: '.create_accessory_unsuccessful'}
      end
    end
  end

  # PUT /accessories/1
  # PUT /accessories/1.json
  def update
    @accessory = Accessory.find(params[:id])

    respond_to do |format|
      if @accessory.update_attributes(params[:accessory])
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory = Accessory.find(params[:id])
    @accessory.destroy

    respond_to do |format|
      format.html { redirect_to accessories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_accessory.html.slim
tr
  td= accessory.name
  td= link_to(image_tag("#{accessory.image}"), category_accessory_path(@category,accessory))
  td= number_to_currency(accessory.price)
  td= accessory.description
  td
    span='link_to(t('.edit'), edit_category_accessory_path(@category,accessory), {class: "btn"})
    span='link_to(t('.destroy'), category_accessory_path(@category,accessory), :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger")
    span=link_to(t('common.add_to_cart'), quote_box_line_items_path(accessory_id: accessory), method: :post, class: "btn")

app/views/accessories/_form.html.slim
= form_for [@category, @accessory], html: {class: "form-horizontal"} do |f|
  fieldset

    legend =t("." + "#{action_name}" + "_accessory")
    =render(partial: 'show_error_message', locals: {obj: @accessory})
    div.control-group(class="#{field_has_error?(@accessory, :name) ? "error" : ""}")
      =f.label :name, t('common.form.name'), class: "control-label"
      .controls
        = f.text_field :name, {placeholder: t("common.form.name"), class: "text_field input-medium"}
        - if field_has_error?(@accessory, :name)
          span.help-inline=get_field_error(@accessory, :name)
    div.control-group(class="#{field_has_error?(@accessory, :description) ? "error" : ""}")
      =f.label :description, t('common.form.description'), class: "control-label"
      .controls
        = f.text_field :description, {placeholder: t("common.form.description"), class: "text_field input-medium"}
        - if field_has_error?(@accessory, :description)
          span.help-inline=get_field_error(@accessory, :description)
    div.control-group(class="#{field_has_error?(@accessory, :price) ? "error" : ""}")
      =f.label :price, t('common.form.price'), class: "control-label"
      .controls
        .input-prepend
          span.add-on $
          = f.text_field :price, {placeholder: t("common.form.price"), class: "span2 text_field input-small"}
        - if field_has_error?(@accessory, :price)
          span.help-inline=get_field_error(@accessory, :price)
    div.control-group(class="#{field_has_error?(@accessory, :displayable_flag) ? "error" : ""}")
      =f.label :displayable_flag, t('common.form.displayable_flag'), class: "control-label"
      .controls
        .make-switch(tabindex="0")
          = f.check_box :displayable_flag
    div.control-group(class="#{field_has_error?(@accessory, :image) ? "error" : ""}")
      =f.label :image, t('common.form.image'), class: "control-label"
      .controls
        = f.file_field :image
        - if field_has_error?(@accessory, :image)
          span.help-inline=get_field_error(@accessory, :image)
    .form-actions
      ='f.submit t('common.form.save'), {class: "btn btn-primary"}
      =link_to(t('common.form.cancel'), :back, {class: "btn"})

app/views/accessories/_form_wrapper.html.slim
-if @accessory.errors.size > 0
  .message
    .ui-widget
      div(class="ui-state-error ui-corner-all" style='padding: 0 .7em;')
        p
          span(class='ui-icon ui-icon-alert' style='float: left; margin-right: .3em;')
          |
          =t('.saving_form_data_error')
/-if @account.errors.size > 0
/  .message
/    .ui-widget
/      div(class="ui-state-highlight ui-corner-all" style='padding: 0 .7em;')
/        p
/          span(class='ui-icon ui-icon-info' style='float: left; margin-right: .3em;')
/          -@account.errors.each do |field, message|
/            =field.to_s.concat(" #{message}").html_safe
/            br
= render "form"

app/views/accessories/edit.html.slim
.row
  .span8(class="offset2")
    == render 'form'


app/views/accessories/index.html.slim
.page-header
  h2=t('.header', in: @category.name)
  small
    =t('.sub_header')
    =render partial: "show_info_message"
table.table(class="table-striped")
  thead
    tr
      th=t('common.table.name')
      th=t('common.table.image')
      th=t('common.table.price')
      th=t('common.table.description')
      th=t('common.table.action')
  tbody
    =render :partial => 'accessory', :collection => @accessories
='link_to(t('.new_accessory'),new_category_accessory_path, class: "btn btn-primary")
=link_to(t('.categories_btn'),categories_path, class: "btn")

app/views/accessories/new.html.slim
.row
  .span8(class="offset2")
    == render 'form'

app/views/accessories/show.html.slim
p#notice = notice


= link_to 'Edit', edit_accessory_path(@accessory)
'|
= link_to 'Back', accessories_path